# This is a basic workflow to help you get started with Actions

name: ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install prerequisites
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == macos* ]]; then
          brew install zsh fish shellcheck
        elif [[ "${{ matrix.os }}" == ubuntu* ]]; then
          sudo apt-add-repository -y ppa:fish-shell/release-3
          sudo apt -y update
          sudo apt -y install zsh fish shellcheck
        fi

    - name: Show version
      run: |
        bash --version; echo
        zsh  --version; echo
        fish --version; echo

    - name: Shellcheck
      run: shellcheck forgit.plugin.sh

    - name: Test bash
      run: bash forgit.plugin.sh

    - name: Test zsh
      run: zsh forgit.plugin.zsh

    - name: Test fish
      run: fish conf.d/forgit.plugin.fish
